# Generated by Django 5.0 on 2024-08-18 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('supplier', models.CharField(blank=True, max_length=100, null=True)),
                ('minimum_threshold', models.PositiveIntegerField(default=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock', to='accounts.site')),
            ],
        ),
        migrations.CreateModel(
            name='Reciept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.site')),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reciepts', to='stock.stock')),
            ],
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['site'], name='stock_stock_site_id_f7e771_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['quantity'], name='stock_stock_quantit_ffb26c_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['price'], name='stock_stock_price_c0622b_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['supplier'], name='stock_stock_supplie_8bf314_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['created'], name='stock_stock_created_505018_idx'),
        ),
        migrations.AddIndex(
            model_name='reciept',
            index=models.Index(fields=['site'], name='stock_recie_site_id_d0686c_idx'),
        ),
        migrations.AddIndex(
            model_name='reciept',
            index=models.Index(fields=['stock'], name='stock_recie_stock_i_abfb97_idx'),
        ),
        migrations.AddIndex(
            model_name='reciept',
            index=models.Index(fields=['created'], name='stock_recie_created_850d4a_idx'),
        ),
    ]
