# Generated by Django 5.0 on 2024-08-13 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_site_company'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reciept',
            index=models.Index(fields=['site'], name='stock_recie_site_id_d0686c_idx'),
        ),
        migrations.AddIndex(
            model_name='reciept',
            index=models.Index(fields=['stock'], name='stock_recie_stock_i_abfb97_idx'),
        ),
        migrations.AddIndex(
            model_name='reciept',
            index=models.Index(fields=['created'], name='stock_recie_created_850d4a_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['site'], name='stock_stock_site_id_f7e771_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['quantity'], name='stock_stock_quantit_ffb26c_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['price'], name='stock_stock_price_c0622b_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['supplier'], name='stock_stock_supplie_8bf314_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['created'], name='stock_stock_created_505018_idx'),
        ),
    ]
