# Generated by Django 5.0 on 2023-12-28 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gas',
            name='minimum_threshold',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
