# Generated by Django 5.0 on 2024-08-14 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingprofile',
            old_name='user',
            new_name='admin',
        ),
    ]
