# Generated by Django 5.0 on 2024-08-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_invoice_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='poll_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
