# Generated by Django 5.0 on 2024-08-13 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_site_company'),
        ('requisition', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='requisition',
            index=models.Index(fields=['site'], name='requisition_site_id_a3906d_idx'),
        ),
        migrations.AddIndex(
            model_name='requisition',
            index=models.Index(fields=['requisition_type'], name='requisition_requisi_8fc3eb_idx'),
        ),
        migrations.AddIndex(
            model_name='requisition',
            index=models.Index(fields=['status'], name='requisition_status_9967f2_idx'),
        ),
        migrations.AddIndex(
            model_name='requisition',
            index=models.Index(fields=['created'], name='requisition_created_1cfd2a_idx'),
        ),
        migrations.AddIndex(
            model_name='requisition',
            index=models.Index(fields=['updated'], name='requisition_updated_a3f600_idx'),
        ),
    ]
