# Generated by Django 5.0 on 2024-08-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_site_status_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Suspended', 'Suspended'), ('Draft', 'Draft')], default='Suspended', max_length=255),
        ),
    ]
