# Generated by Django 5.0 on 2023-12-28 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='unit_cost',
        ),
    ]
