# Generated by Django 5.0 on 2024-06-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='customer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
