# Generated by Django 5.0 on 2024-06-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transaction_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
    ]
