# Generated by Django 5.0 on 2024-06-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transaction_unit_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='order_number',
            field=models.CharField(blank=True, editable=False, max_length=36, unique=True),
        ),
    ]
