name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py collectstatic
        python manage.py test

      env:
          SECRET_KEY: "django-insecure-c0y7^zo53cwo$0!4(7ife!=%$46wk=6*)g$rgivz41uncm%z@)"
          DEBUG: 1
          MONGO_DB_PSW_SECRET_KEY: "YvHrQvg1D349k1OXF3-BHpScqfORC1CWC9NfVXG1bUM="
          USE_MYSQL: False
          MYSQL_DB_NAME: "l"
          MYSQL_DB_USER: "rt"
          MYSQL_DB_PASSWORD: "paord"
          MYSQL_DB_HOST: "127.3.0.1"
          MYSQL_DB_PORT: "3386"
          EMAIL_HOST: "smtp.of5.com"
          EMAIL_PORT: 5123
          EMAIL_HOST_USER: ""
          DEFAULT_FROM_EMAIL: "am"
          EMAIL_HOST_PASSWORD: "@l"
          EMAIL_USE_TLS: True
          DEFAULT_RECIPIENT: "n"
          FERNET_KEY: "g8Axb5a090hDBAv2N9AFW6btpONavFqLIruakUEGKtc="